# basic options
title: Your awesome title
author: This Girl
email: your-email@domain.com
description: A wonderful site
twitter_username: jekyllrb
github_username: kowskysur

# Build settings
markdown: kramdown
theme: minima

collections:
  animals:
    output: true
